Feat : 회원 가입 및 회원 ID 조회 구현
gyureal/codeReviewStudy pull request #5
Opened 2023-09-10 15:33 UTC by woojkk

회원가입 : 가입 시 해당 아이디가 존재하는지 확인하고 있다면 CustomException을 던지도록 했고
user객체를 만들어서 값을 설정한뒤 저장하도록 구현했습니다.

Id 조회 : CRUDRepsitory를 상속받아 기본 findById를 통해 해당하는 아이디를 조회하도록 했고 해당 아이디를 가진 유저가 없다면 
예외를 던지도록 했습니다.

2023-09-11 04:04 UTC, gyureal requested changes
1. 현재 단계에서는 실제 DB와 JPA를 사용하는 것이 요구사항이었습니다.
gradle에서 JPA의존성을 지워주시고 다시 한번 고민해보세요. 
[Hint] 
- 데이터 저장은 실제 DB가 아닌 Map을 사용하면됩니다.
- 나중에 JPA로 변환시키게됩니다.

2. 공통예외처리 기능은 아직 구현하지 않습니다. 해당 내용은 지금 단계에서는 지워주세요

2023-09-11 04:04 UTC, gyureal commented on src/test/java/com/example/codereviewstudy/controller/UserControllerTest.java
> +@WebMvcTest(UserController.class)
WebMvcTest와 SpringBootTest의 차이점은 무엇인가요?

2023-09-11 08:12 UTC, woojkk commented on src/main/java/com/example/codereviewstudy/controller/UserController.java
> +@Controller
@Controller는 view를 반환할때 사용하고
@RestController는 @Controller + @ResponseBody 로 JSON형태의 데이터를 반환할 때 사용합니다.

2023-09-11 08:12 UTC, woojkk commented on src/main/java/com/example/codereviewstudy/controller/UserController.java
> +  public ResponseEntity<?> searchUser(@PathVariable long userId) {
제네릭은 타입 안정성을 위해 사용하기 떄문에
wild카드를 사용하면 의미가 없어집니다!
수정하겠습니다!

2023-09-11 08:12 UTC, woojkk commented on src/main/java/com/example/codereviewstudy/controller/UserController.java
> +        userService.searchUser(userId));
dto는 주로 뷰와 controller 사이나 계층 간 데이터 전송을 목적으로 사용되고
entity는 db와 매핑되기 때문에 뷰에 접근할떄 사용하게되면 데이터가 변경될 위험이 있습니다.
따라서 분리하여 dto는 presentation, entity는 persistence를 위해 사용해야합니다.

2023-09-11 08:15 UTC, woojkk commented on src/main/java/com/example/codereviewstudy/domain/model/User.java
> +  public void setId(long userId) {
생성인지 수정인지 명확하지 않고
의도치 않게 entity의 값이 변경될 수 있습니다.

2023-09-11 08:39 UTC, woojkk commented on src/main/java/com/example/codereviewstudy/exception/CustomException.java
> +public class CustomException extends RuntimeException {
CustomException을 사용하면 이름으로 정보 전달이 가능하고
상세한 정보를 제공하는게 가능해집니다.
하지만 현재 CustomException은 표준 예외로도 충분히 처리 가능하기 때문에
표준에외를 사용하도록 수정하겠습니다.

2023-09-11 09:01 UTC, woojkk commented on src/test/java/com/example/codereviewstudy/controller/UserControllerTest.java
> +@WebMvcTest(UserController.class)
@SpringBootTest는 통합테스트로 spring이 관리하는 모든 빈을 등록시켜서 속도는 느리지만
실제 환경과 유사한 테스트가 가능하고 변경에 자유롭습니다.
@WebMvcTest는 속도가 빠르고 통합 테스트가 어려운 테스트를 개별적으로 진행이 가능합니다.
실제 환경과는 차이가 있고 변경에 자유롭지 못합니다.

2023-09-12 03:02 UTC, gyureal approved these changes
네 전체적으로 제가 의도한 방향 대로 잘 구현하신 것 같습니다
코멘트 하나 달아두었으니 확인해주세요

2023-09-12 03:02 UTC, gyureal commented on src/main/java/com/example/codereviewstudy/service/UserService.java
> +  private long newId = 0;
newId가 서비스에 존재하는 것이 서비스의 책임에 부합하는지 궁금합니다
지금은 Map을 사용하지만 나중에 JPA를 쓰게 된다면 어떨까요?
객체지향의 개방 폐쇄 원칙에 따라서 기존 기능의 수정 없이 변경이 가능해야 좋은 구조라고 생각합니다

2023-09-12 09:21 UTC, merged